export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS || "0x5FbDB2315678afecb367f032d93F642f64180aa3";

export const FLASH_USDT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
  "function flashIdCounter() view returns (uint256)",
  "function defaultFlashTTL() view returns (uint256)",
  "function gasWallet() view returns (address)",
  "function flashGasFee() view returns (uint256)",
  "function flashBalance(address) view returns (uint256)",
  "function flashQuota(address) view returns (uint256)",
  "function flashQuotaUsed(address) view returns (uint256)",
  "function remainingQuota(address) view returns (uint256)",
  "function realBalance(address) view returns (uint256)",
  "function isBlacklisted(address) view returns (bool)",
  "function isDEXBlocked(address) view returns (bool)",
  "function isFlashExpired(uint256) view returns (bool)",
  "function getFlashTransfer(uint256) view returns (address sender, address recipient, uint256 amount, uint256 expiresAt, bool invalidated, bool reclaimed, bool expired)",
  "function allowance(address,address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "function destroy(address from, uint256 amount)",
  "function burn(uint256 amount)",
  "function pause()",
  "function unpause()",
  "function blacklist(address account)",
  "function unBlacklist(address account)",
  "function blockDEX(address dexAddress)",
  "function unblockDEX(address dexAddress)",
  "function setGasWallet(address newWallet)",
  "function setGasFee(uint256 newFee)",
  "function setQuota(address account, uint256 quota)",
  "function setDefaultFlashTTL(uint256 ttl)",
  "function setDecimals(uint8 newDecimals)",
  "function flashTransfer(address to, uint256 amount) returns (uint256)",
  "function flashTransferWithTTL(address to, uint256 amount, uint256 ttl) returns (uint256)",
  "function invalidateFlash(uint256 flashId)",
  "function reclaimFlash(uint256 flashId)",
  "function batchReclaim(uint256 fromId, uint256 toId)",
  "function transferOwnership(address newOwner)",
  "event FlashSent(uint256 indexed flashId, address indexed sender, address indexed recipient, uint256 amount, uint256 expiresAt)",
  "event FlashInvalidated(uint256 indexed flashId)",
  "event FlashReclaimed(uint256 indexed flashId, uint256 amount)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Mint(address indexed to, uint256 amount)",
  "event Destroy(address indexed from, uint256 amount)",
  "event Blacklisted(address indexed account)",
  "event UnBlacklisted(address indexed account)",
  "event DEXBlocked(address indexed account)",
  "event DEXUnblocked(address indexed account)",
  "event QuotaSet(address indexed account, uint256 quota)",
  "event GasWalletUpdated(address indexed newWallet)",
  "event GasFeeUpdated(uint256 newFee)",
  "event DecimalsUpdated(uint8 newDecimals)",
  "event Paused(address account)",
  "event Unpaused(address account)",
] as const;
